webserver:
  port: 8080
  host: 0.0.0.0
minecraft-server:
  directory: mc-server
  start-command: /home/pipeman/.jdks/zulu21.32.17-ca-jre21.0.2-linux_x64/bin/java
    -jar paper-1.21.1-120.jar nogui
  console-history:
    max-lines: 10000
server-port: 8080
