webserver:
  port: 8080
  host: 0.0.0.0
minecraft-server:
  console-history:
    max-lines: 10000
mod-platforms:
  curseforge:
    api-key: $2a$10$9EWg4HOI4HEkBhFUWlNN6e7Xh8PI2C/gGPD/1.8zw4hZxRWMpgy6a
server-port: 8080
